const os = require('os');
// console.log(os.version());
// console.log(os.platform());
// console.log(os.hostname());
// console.log(os.EOL);
// console.log(os.networkInterfaces());
// console.log(os.uptime());
// console.log(os.release());
// console.log(os.freemem());
// console.log(os.type());